name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest] # ubuntu-latest, windows-latest
        ghc: ["8.10.7"]
        cabal: ["latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          
      - name: Cabal freeze
        run: |
          cabal v2-update
          cabal v2-freeze --enable-tests --enable-benchmarks
          
      - name: Cache ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: ${{ matrix.os }}-GHC-${{ matrix.ghc }}-${{ hashFiles('cabal.project.ci.freeze') }}
          restore-keys: ${{ matrix.os }}-GHC-${{ matrix.ghc }}-

      - name: Cabal build
        run: |
          cabal v2-build


        
